services:
  database:
    container_name: crawler_test_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_test
      MYSQL_USER: symfony_test
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
  php:
    container_name: crawler_test_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/crawler-test
    depends_on:
      - database
  nginx:
    container_name: crawler_test_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/crawler-test
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  rabbitmq:
    container_name: crawler_test_rabbitmq
    image: rabbitmq:3.8.2-management
    ports: [5672, 15672]
